### ISSUE TITLE
Develop sample content for all major components

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/schemas#133]
Right now our simple examples are very focused on Indicator, but we should expand that to include examples of incidents, courses of action, TTPs, etc.

**Comment by johnwunder** [comment]
@bschmoker is right, this isn't true anymore.

**Comment by athiasjerome** [comment]
was related to my question regarding Behavior-driven development, or in shorter terms: we need samples for unit testing and non-regression testing... of STIX tools
