### ISSUE TITLE
Annotations for ActivityType in Campaign are incorrect

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/schemas#137]
"The Activity field characterizes actions taken in regards to this ThreatActor. This field is defined as of type ActivityType which is an abstract type enabling the extension and inclusion of various formats of Activity characterization."

That should probably say:

"The Activity field characterizes actions taken in regards to this **Campaign**. This field is defined as of type ActivityType which is an abstract type enabling the extension and inclusion of various formats of Activity characterization."

**Comment by bschmoker** [comment]
@rpiazza - Does this commit look good?
