### ISSUE TITLE
Indicator/Type field annotation references wrong default vocabulary

### ISSUE THREAD

**Issue by ikiril01** [STIXProject/schemas#180]
The annotation for the Type field in the IndicatorType of the Indicator schema currently reads: "The default vocabulary type is IndicatorTypeVocabularyType...". The actual default vocabulary should be "IndicatorTypeVocab-1.1".

**Comment by bschmoker** [comment]
@sbarnum Are there add'l changes to make w.r.t. this issue that weren't covered in c79b7ec
?

**Comment by rpiazza** [comment]
This issue is complete.
