### ISSUE TITLE
AssetTypeEnum contains duplicate entries

### ISSUE THREAD

**Issue by rpiazza** [STIXProject/schemas#217]
Media is listed twice.
Telephone is listed twice

**Comment by bschmoker** [comment]
@rpiazza - Does this close the issue?

**Comment by rpiazza** [comment]
@bschmoker - This looks good to me, and I can't think of any reasonable test cases - so I would create a pull request - assign it to @gtback - have him run the regression tests in the 1.2 branch, then close this issue - does that order make sense?

**Comment by bschmoker** [comment]
@rpiazza - PR #258 is created

tests are already included under [https://github.com/STIXProject/schemas-test/pull/1](this branch to the test suite) which will be auto-checked w/ CI once that one is merged

**Comment by rpiazza** [comment]
@sbarnum  @bschmoker - Ben and I think there is no reason to introduce a new version for this vocab, since we are just deleting duplicates.  Agree???

**Comment by rpiazza** [comment]
@johnwunder - see previous comment - what do you think?

**Comment by johnwunder** [comment]
I agree. There's no functional change so no reason to version it.

**Comment by rpiazza** [comment]
ok, then -  @gtback should merge, then I guess a regression test in version1.2 branch, then close...

**Comment by bschmoker** [comment]
@rpiazza @gtback Tests already exist and will be run automatically once [this branch](https://github.com/STIXProject/schemas-test/pull/1) is merged
