### ISSUE TITLE
Use current commit of schemas when running tests

### ISSUE THREAD

**Issue by gtback** [STIXProject/schemas#269]
The `.travis.yml` config should be modified to pass `--schema-dir .` to stix-validator. Otherwise we are running the tests against the 1.1.1 schemas bundled with stix-validator.

https://github.com/STIXProject/schemas-test/blob/977fa72020276f2cd7f4d66dc0a9c46649fe8daf/runner.py#L75-L81

**Comment by bschmoker** [comment]
merged
