### ISSUE TITLE
Time stamps should use ISO8601 format

### ISSUE THREAD

**Issue by jordan2175** [STIXProject/schemas#284]
We should call out in the spec and in the docs / best practices guides that all time stamps MUST use ISO8601 format yyyy-mm-ddThh:mm:ss+-hh:mm

We need critical things like this to be done ALL the same way and not left open to interpretation.

**Comment by johnwunder** [comment]
This is specified canonically in the schemas: all of the date/time types use one of xsd:dateTime, xsd:date, xsd:time, etc. Those each require the use of ISO8601. The UML/spec documents will do the same.

Thus this is already specified as a MUST requirement. Note that, additionally, unlike ISO8601 which leaves it open, STIX strongly suggests a timezone offset be used.

Do you think we need to put it anywhere in particular in the user documentation?

**Comment by jordan2175** [comment]
Putting things in the XSDs, does not really mean people will know what to do.  I think there is a general academic disconnect with people's understand of XML and peoples desire to learn XML or have the tools to read and understand XSDs.  As I have stated many times, academics love XML, developers ask for anything but XML.  Now with that said, I think we need to call it out in the user docs.  So on the Idiom pages where we have a timestamp field, we should put details there that say "Timestamp MUST follow the ISO8601 format and SHOULD (though I would like to see it changed to MUST) include a time zone.  The format MUST be in the version of ISO8601: yyyy-mm-ddThh:mm:ss+-hh:mm

The reason for changing it to a MUST is because without a timezone, it really is meaningless in a world wide connected network.  The fact that you could be off by as much as 24 hours in hunting for something is very problematic.

**Comment by jonathanbaker** [comment]
@jordan2175 I added an issue for the documentation update in our suggested practices. Thanks for pointing it out: https://github.com/STIXProject/stixproject.github.io/issues/178

This new issue would simply add the documentation suggesting the format for the current version of STIX.

**Comment by gtback** [comment]
Can this be closed?

**Comment by johnwunder** [comment]
We need to close this one and open a new one regarding requiring timezone offset for STIX 2.0.

**Comment by gtback** [comment]
Closed in favor of #294
