### ISSUE TITLE
UML models should standardize case for field names

### ISSUE THREAD

**Issue by jordan2175** [STIXProject/schemas#292]
The UML models really need to have a standardized case for field names.  Some of the fields in the UML models are lower case and some are first letter upper case.  I understand that certain implementations will choose to have some field names be lower case and some be first character upper case as in the case with XML and element values versus attributes, but this should not be part of a universal top level specification.

**Comment by rpiazza** [comment]
Closing this issue - issues for the specifications will be in the specification repo's issue tracker (https://github.com/STIXProject/specifications/issues/2)
