### ISSUE TITLE
Information Source field name discrepancies

### ISSUE THREAD

**Issue by jonathanbaker** [STIXProject/schemas#304]
Reported by Brett Jordan:

On the RelatedIdentityType the field name is "Information_Source" 
http://stixproject.github.io/data-model/1.1.1/stixCommon/RelatedIdentityType/

And on the ConfidenceType the field is called "Source"
http://stixproject.github.io/data-model/1.1.1/stixCommon/ConfidenceType/

Can we standardize the field names?  I am guessing these are not the only two that are different.

**Comment by johnwunder** [comment]
Duplicate of #263
