### ISSUE TITLE
Use DateTimeWithPrecisionType in the ConfidenceType

### ISSUE THREAD

**Issue by jonathanbaker** [STIXProject/schemas#305]
Reported by Bret Jordan:

In the confidence type (http://stixproject.github.io/data-model/1.1.1/stixCommon/ConfidenceType/)  we have defined both a:
@timestamp dateTime
and a
@timestamp_precision DateTimePrecisionEnum

However, in the Stix:Common NS we already have a:
DateTimeWithPrecisionType

That should take care of that.  Why not just use it?

**Comment by johnwunder** [comment]
This is done for backwards-compatibility reasons: we had the existing `@timestamp` attribute on `ConfidenceType` in v1.0 and when we moved to v1.1 and added the precision fields we were not able to move that to an element in able to leverage `DateTimeWithPrecisionType`.

This is tracked in #283.
