### ISSUE TITLE
Clarify the usage of IncidentType/Contact or remove it if there's no defined meaning

### ISSUE THREAD

**Issue by rpiazza** [STIXProject/schemas#322]
In `incident.xsd`, the `IncidentType/Contact` field is ambiguous. There are already fields for reporter, responder, coordinator, and victim so it's unclear what `Contact` is meant to be used for.

It's possible that this was added at the request of US-CERT.

**Comment by johnwunder** [comment]
Turns out this is a dup of #238, closing.
