### ISSUE TITLE
Create a new top-level construct to act as common basis for all IDable constructs in STIX

### ISSUE THREAD

**Issue by sbarnum** [STIXProject/schemas#372]
Currently there are a range of different "IDable" constructs in STIX that share a common set of properties such as id, idref, timestamp, Title, Description, etc.

Currently this set of common properties are defined separately on each and every IDable construct leading to complexity and risk of them getting out of sync.

It is proposed that a common IDable Construct (or whatever name makes the most sense) construct be defined with these properties and then all the other IDable construct instances are defined as extensions from this common basis adding their localized properties as appropriate.

**Comment by athiasjerome** [comment]
Yes, but needs another name. (i.e. CommonProperties)

For reference, somehow similar approach in XORCISM by use of a CreationObject, to capture common properties linked to the creation of an object (timestamp, source(asset), confidence, suspicious-flag, ..)
(also abstracted a ChangeRecord object)
(Title, Description not considered as applicable to all objects with these words. btw Description is abstracted in XORCISM, with support of Locales ('languages') and Versioning)

For ID and IDREFS, I would not abstract them in the same way/construct (can provide details later on)

**Comment by sbarnum** [comment]
This is a duplicate of #148 
Closing this issue
