### ISSUE TITLE
Remove usages of xs:float and xs:double

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/schemas#373]
These can lead to rounding errors, in cases where exact calculations are required it would be better to use an integer instead.

(Reported by a MITRE colleague)

**Comment by rpiazza** [comment]
FYI, in the UML specification basicDataTypes:Decimal, which corresponds to xs:decimal, instead of xs:float.

**Comment by johnwunder** [comment]
Good point, looks like the field was in CybOX. Going to open an issue in that tracker.
