### ISSUE TITLE
Add Extension Mechanism for STIXHeaderType in Core

### ISSUE THREAD

**Issue by ikiril01** [STIXProject/schemas#38]
We should consider adding a simple extension mechanism to the STIXHeaderType for capturing any custom header-related entities that users may want to capture; something like simple key/value pairs, akin to the CustomPropertiesType in the cyboxCommon:ObjectProperties, would likely be sufficient for 90% of use cases.

**Comment by johnwunder** [comment]
I'm going to close and re-open now that this applies more to reports than packages. Now #337.
